=== ETS-Android5/alexistudies/audit-log-module/audit-log-service/src/main/resources/audit-log-event-schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"type": "object",
	"additionalProperties": false,
	"required": [
		"alert",
		"user_id",
		"system_id",
		"event_info",
		"event_name",
		"correlation_id",
		"event_timestamp"
	],
	"properties": {
		"alert": {
			"type": "boolean"
		},
		"app_id": {
			"type": "string"
		},
		"org_id": {
			"type": "string"
		},
		"user_id": {
			"type": "string"
		},
		"system_id": {
			"type": "string",
			"minLength":3
		},
		"event_name": {
			"type": "string",
			"minLength":3
		},
		"correlation_id": {
			"type": "string",
			"minLength":10
		},
		"event_timestamp": {
			"type": "integer"
		},
		"event_info": {
			"type": "object",
			"additionalProperties": false,
			"required": [
				"system_ip",
				"description",
				"event_detail",
				"application_version",
				"application_component_name"
			],
			"properties": {
				"email": {
					"type": "string"
				},
				"client_id": {
					"type": "string"
				},
				"system_ip": {
					"type": "string",
					"minLength":7
				},
				"description": {
					"type": "string",
					"minLength":1
				},
				"device_type": {
					"type": "string"
				},
				"request_uri": {
					"type": "string"
				},
				"access_level": {
					"type": "string"
				},
				"event_detail": {
					"type": "string",
					"minLength":1
				},
				"device_platform": {
					"type": "string"
				},
				"resource_server": {
					"type": "string"
				},
				"client_app_version": {
					"type": "string"
				},
				"application_version": {
					"type": "string",
					"minLength":1
				},
				"client_access_level": {
					"type": "string"
				},
				"application_component_name": {
					"type": "string",
					"minLength":1
				}
			}
		}
	}
}

=== ETS-Android5/alexistudies/audit-log-module/audit-log-service/src/test/resources/valid_audit_log_event.json
{
	"alert": false,
	"app_id": "MyStudies",
	"org_id": "FDA",
	"user_id": "dc526f64-968e-4d41-82ac-6fc4fbffbf11f",
	"system_id": "FMSGCAUTHSVR",
	"event_name": "REGISTRATION_SUCCESS",
	"correlation_id": "145ee4b2-f1d2-44b6-85b9-d7a04f8b7e91",
	"event_timestamp": 1589961168227,
	"event_info": {
		"email": "oauth_scim_user2@grr.la",
		"client_id": "FMSGCPARDTST",
		"system_ip": "192.168.0.18",
		"description": "App user registration successful for username oauth_scim_user2@grr.la and user ID dc526f64-968e-4d41-82ac-6fc4fbffbf11f returned to Resource Server",
		"device_type": "desktop",
		"request_uri": "/oauth-scim-service/v1/users",
		"access_level": "App-User",
		"event_detail": "App user registration success",
		"device_platform": "windows",
		"resource_server": "Participant Datastore",
		"client_app_version": "v1.0",
		"application_version": "v1.0",
		"client_access_level": "System-level",
		"application_component_name": "Auth Server"
	}
}
